In [39]:
import torch
import torch.nn.functional as F
import numpy as np
from details import *

In [40]:
B,C_in,H,W=1,1,4,4
C_out,C_in,Kh,Kw,=1,1,2,2

In [41]:
X=torch.randint(1, 10, (B, C_in, H, W))
Weight=torch.randint(1, 10, (C_out,C_in,Kh,Kw))

In [42]:
X_tilde=sample_X(X,1,1)
print("X:\n",X[0,0])
print("X_tilde:\n",X_tilde[0,0])

X:
 tensor([[8, 7, 5, 4],
        [3, 8, 6, 6],
        [7, 6, 7, 5],
        [1, 6, 8, 7]])
X_tilde:
 tensor([[8, 7, 5, 4],
        [3, 8, 6, 6],
        [7, 6, 7, 5],
        [1, 6, 8, 7]])


In [43]:
X_tilde=sample_X(X,2,2)
print("X:\n",X[0,0])
print("X_tilde:\n",X_tilde[0,0])

X:
 tensor([[8, 7, 5, 4],
        [3, 8, 6, 6],
        [7, 6, 7, 5],
        [1, 6, 8, 7]])
X_tilde:
 tensor([[8, 5],
        [7, 7]])


In [44]:
X_tilde=sample_X(X,1/2,1/2)
print("X:\n",X[0,0])
print("X_tilde:\n",X_tilde[0,0])

X:
 tensor([[8, 7, 5, 4],
        [3, 8, 6, 6],
        [7, 6, 7, 5],
        [1, 6, 8, 7]])
X_tilde:
 tensor([[8, 0, 7, 0, 5, 0, 4, 0],
        [0, 0, 0, 0, 0, 0, 0, 0],
        [3, 0, 8, 0, 6, 0, 6, 0],
        [0, 0, 0, 0, 0, 0, 0, 0],
        [7, 0, 6, 0, 7, 0, 5, 0],
        [0, 0, 0, 0, 0, 0, 0, 0],
        [1, 0, 6, 0, 8, 0, 7, 0],
        [0, 0, 0, 0, 0, 0, 0, 0]])


In [45]:
# Y_my=unified_conv(X, Weight,
#                   Tx=1,Ty=1,
#                   Sx=2,Sy=2,
#                   pad=0)
# print(f"Y_my:{Y_my.shape}\n",Y_my)
print("X",X)
print("Weight",Weight)
# X_in=sample_X(X,1/2,1/2)
# print(X_in)
# Y_official=F.conv2d(X,Weight,bias=None,stride=(2,2))
# print(f"Y_official{Y_official.shape}\n",Y_official)
Y_official=F.conv_transpose2d(X,Weight.transpose(0,1),bias=None,stride=(2,2))
print(f"Y_official{Y_official.shape}\n",Y_official)

tensor([[[[8, 7, 5, 4],
          [3, 8, 6, 6],
          [7, 6, 7, 5],
          [1, 6, 8, 7]]]])
tensor([[[[1, 3],
          [4, 9]]]])
Y_officialtorch.Size([1, 1, 8, 8])
 tensor([[[[ 8, 24,  7, 21,  5, 15,  4, 12],
          [32, 72, 28, 63, 20, 45, 16, 36],
          [ 3,  9,  8, 24,  6, 18,  6, 18],
          [12, 27, 32, 72, 24, 54, 24, 54],
          [ 7, 21,  6, 18,  7, 21,  5, 15],
          [28, 63, 24, 54, 28, 63, 20, 45],
          [ 1,  3,  6, 18,  8, 24,  7, 21],
          [ 4,  9, 24, 54, 32, 72, 28, 63]]]])
