In [1]:
import torch
import torch.nn.functional as F
import numpy as np
from details import *

In [2]:
B,C_in,H,W=1,2,9,9
C_out,C_in,Kh,Kw,=1,2,4,4

In [3]:
X=torch.randint(1, 10, (B, C_in, H, W))
Weight=torch.randint(1, 10, (C_out,C_in,Kh,Kw))

In [4]:
X_tilde=sample_X(X,1,1)
print("X:\n",X[0,0])
print("X_tilde:\n",X_tilde[0,0])

X:
 tensor([[3, 8, 4, 8, 1, 7, 1, 3, 7],
        [2, 3, 4, 5, 7, 9, 5, 9, 1],
        [2, 8, 8, 2, 3, 9, 1, 6, 5],
        [1, 4, 3, 8, 4, 4, 9, 1, 5],
        [5, 8, 9, 2, 7, 8, 4, 5, 7],
        [2, 6, 9, 8, 9, 3, 4, 2, 7],
        [3, 2, 6, 2, 7, 3, 8, 2, 3],
        [3, 5, 8, 5, 9, 7, 6, 4, 7],
        [8, 1, 1, 2, 3, 9, 7, 8, 1]])
X_tilde:
 tensor([[3, 8, 4, 8, 1, 7, 1, 3, 7],
        [2, 3, 4, 5, 7, 9, 5, 9, 1],
        [2, 8, 8, 2, 3, 9, 1, 6, 5],
        [1, 4, 3, 8, 4, 4, 9, 1, 5],
        [5, 8, 9, 2, 7, 8, 4, 5, 7],
        [2, 6, 9, 8, 9, 3, 4, 2, 7],
        [3, 2, 6, 2, 7, 3, 8, 2, 3],
        [3, 5, 8, 5, 9, 7, 6, 4, 7],
        [8, 1, 1, 2, 3, 9, 7, 8, 1]])


In [5]:
X_tilde=sample_X(X,2,2)
print("X:\n",X[0,0])
print("X_tilde:\n",X_tilde[0,0])

X:
 tensor([[3, 8, 4, 8, 1, 7, 1, 3, 7],
        [2, 3, 4, 5, 7, 9, 5, 9, 1],
        [2, 8, 8, 2, 3, 9, 1, 6, 5],
        [1, 4, 3, 8, 4, 4, 9, 1, 5],
        [5, 8, 9, 2, 7, 8, 4, 5, 7],
        [2, 6, 9, 8, 9, 3, 4, 2, 7],
        [3, 2, 6, 2, 7, 3, 8, 2, 3],
        [3, 5, 8, 5, 9, 7, 6, 4, 7],
        [8, 1, 1, 2, 3, 9, 7, 8, 1]])
X_tilde:
 tensor([[3, 4, 1, 1, 7],
        [2, 8, 3, 1, 5],
        [5, 9, 7, 4, 7],
        [3, 6, 7, 8, 3],
        [8, 1, 3, 7, 1]])


In [6]:
X_tilde=sample_X(X,1/2,1/2)
print("X:\n",X[0,0])
print("X_tilde:\n",X_tilde[0,0])

X:
 tensor([[3, 8, 4, 8, 1, 7, 1, 3, 7],
        [2, 3, 4, 5, 7, 9, 5, 9, 1],
        [2, 8, 8, 2, 3, 9, 1, 6, 5],
        [1, 4, 3, 8, 4, 4, 9, 1, 5],
        [5, 8, 9, 2, 7, 8, 4, 5, 7],
        [2, 6, 9, 8, 9, 3, 4, 2, 7],
        [3, 2, 6, 2, 7, 3, 8, 2, 3],
        [3, 5, 8, 5, 9, 7, 6, 4, 7],
        [8, 1, 1, 2, 3, 9, 7, 8, 1]])
X_tilde:
 tensor([[3, 0, 8, 0, 4, 0, 8, 0, 1, 0, 7, 0, 1, 0, 3, 0, 7, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [2, 0, 3, 0, 4, 0, 5, 0, 7, 0, 9, 0, 5, 0, 9, 0, 1, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [2, 0, 8, 0, 8, 0, 2, 0, 3, 0, 9, 0, 1, 0, 6, 0, 5, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 0, 4, 0, 3, 0, 8, 0, 4, 0, 4, 0, 9, 0, 1, 0, 5, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [5, 0, 8, 0, 9, 0, 2, 0, 7, 0, 8, 0, 4, 0, 5, 0, 7, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [2, 

In [7]:
Y_my=compute_conv2d(X, Weight,stride=2,pad=0)
print(f"Y_my:{Y_my.shape}\n",Y_my)
# Y_my=compute_transconv(X,Weight,stride=2)
# print("X",X)
# print("Weight",Weight)
# X_in=sample_X(X,1/2,1/2)
# print(X_in)
Y_official=F.conv2d(X,Weight,bias=None,stride=2)
print(f"Y_official{Y_official.shape}\n",Y_official)

torch.all(Y_official.int()==Y_my.int())

Y_my:torch.Size([1, 1, 3, 3])
 tensor([[[[663., 788., 813.],
          [784., 847., 803.],
          [832., 902., 815.]]]])
Y_officialtorch.Size([1, 1, 3, 3])
 tensor([[[[663, 788, 813],
          [784, 847, 803],
          [832, 902, 815]]]])


tensor(True)

In [8]:
# print("X",X)
# print("Weight",Weight)
Y_my=compute_transconv(X,Weight.transpose(0,1),stride=2)

print(f"Y_my{Y_my.shape}\n",Y_my)
Y_official=F.conv_transpose2d(X,Weight.transpose(0,1),bias=None,stride=2)
print(f"Y_official{Y_official.shape}\n",Y_official)

torch.all(Y_official.int()==Y_my.int())

Y_mytorch.Size([1, 1, 20, 20])
 tensor([[[[ 52.,  23.,  91.,  90.,  51.,  80.,  31.,  56.,  88.,  75., 102.,
            87.,  60.,  69.,  50.,  39.,  86.,  71.,  70.,  84.],
          [ 20.,  78.,  77., 125.,  94.,  74.,  58.,  68.,  96., 117.,  65.,
           128.,  83.,  74.,  33.,  66.,  67., 128.,  91.,  70.],
          [ 71.,  70., 153., 192., 156., 169., 112., 148., 163., 188., 217.,
           268., 177., 220.,  99., 144., 133., 196.,  89., 129.],
          [ 69., 107., 166., 164., 166., 204., 177., 140., 181., 266., 222.,
           249., 206., 230., 130., 144., 216., 166.,  77.,  94.],
          [ 61.,  54., 122., 169., 121., 203., 134., 182., 158., 180., 224.,
           289., 214., 286., 156., 173., 151., 198.,  35.,  69.],
          [ 52.,  92., 124., 160., 186., 174., 179., 156., 187., 208., 251.,
           297., 252., 240., 182., 202., 181., 207.,  59.,  34.],
          [ 88.,  59., 153., 179., 163., 177., 168., 204., 106., 178., 151.,
           198., 209., 255., 164.

tensor(True)